package com.example.crypto.adapters.in.web.dto;

import io.swagger.v3.oas.annotations.media.Schema;

import java.net.URI;
import java.util.List;

/**
 * OpenAPI-friendly representation of RFC7807 Problem Details.
 *
 * <p>Spring exposes {@code org.springframework.http.ProblemDetail} at runtime, but for a stable API contract
 * documented a dedicated schema that includes custom properties used by this service (e.g. symbol, violations).
 */
@Schema(name = "ApiProblem", description = "RFC7807 Problem Details (application/problem+json)")
public record ProblemDetailDto(
        @Schema(description = "A URI reference that identifies the problem type") URI type,
        @Schema(description = "A short, human-readable summary of the problem type") String title,
        @Schema(description = "The HTTP status code generated by the origin server") Integer status,
        @Schema(description = "A human-readable explanation specific to this occurrence of the problem") String detail,
        @Schema(description = "A URI reference that identifies the specific occurrence of the problem") String instance,

        // common custom extensions used by this service
        @Schema(description = "Crypto symbol related to the error", example = "BTC") String symbol,
        @Schema(description = "Validation violations (field: message)") List<String> violations,
        @Schema(description = "Client IP used for rate limiting", example = "1.2.3.4") String clientIp
) {
}
